### ISSUE TITLE
Server console hangs

### ISSUE THREAD

**Issue by gegtor** [SmartlyDressedGames/Legally-Distinct-Missile#12]
With the latest game provided rocket module console hangs on following
<img width="1320" alt="Screenshot 2020-05-13 at 02 55 16" src="https://user-images.githubusercontent.com/10978723/81759520-411b5580-94c5-11ea-9dcf-f414a441500f.png">

Making managing the server very hard

But the server starts normally 

`unturned.log`
```[registered] /unadmin (Rocket.Unturned.Commands.CommandUnadmin/unadmin)
[registered] /v (Rocket.Unturned.Commands.CommandV/v)
[registered] /vanish (Rocket.Unturned.Commands.CommandVanish/vanish)
This server will automatically save every 1800 seconds
Steam servers ready!
Workshop install folder: /home/ubuntu/Unturned_Server/Servers/server-1/Workshop/Steam
0 workshop item(s) requested
Unloading 2 Unused Serialized files (Serialized files now loaded: 2)
UnloadTime: 0.210000 ms
Loading level: 8%

Unloading 7 unused Assets to reduce memory usage. Loaded Objects now: 13225.
Total: 159.431000 ms (FindLiveObjects: 1.295000 ms CreateObjectMapping: 0.722000 ms MarkObjects: 157.335000 ms  DeleteObjects: 0.077000 ms)

Unloading 1 Unused Serialized files (Serialized files now loaded: 2)

Unloading 0 unused Assets to reduce memory usage. Loaded Objects now: 13225.
Total: 159.096000 ms (FindLiveObjects: 1.188000 ms CreateObjectMapping: 0.675000 ms MarkObjects: 157.182000 ms  DeleteObjects: 0.051000 ms)

Loading level: 16%
Loading level: 25%
Loading level: 33%
Loading level: 41%
Loading level: 50%
Loading level: 58%
Loading level: 66%
Loading level: 75%
Loading level: 83%
Loading level: 91%
Loading level: 100%
UnloadTime: 72.390000 ms
Setting up 1 worker threads for Enlighten.
  Thread -> id: 7f388e9de700 -> priority: 1
```

**Comment by SDGNelson** [comment]
If you launch it the recommended way as discussed in the other thread does it work?
    
    ./ServerHelper.sh -ThreadedConsole +LanServer/XYZ

(Without any changes to the script.)

**Comment by gegtor** [comment]
https://github.com/gegtor/Unturned-64Bit-Server-Scripts 
I'm using my own script based on RocketMod scripts

**Comment by SDGNelson** [comment]
RocketLauncher is unnecessary and should probably be removed. I think Trojaner brought the removal of RocketLauncher up recently but I can't find his comment. You can probably completely get rid of the repository you linked.

**Comment by gegtor** [comment]
I find default scripts unreliable and so do 10 people that asked me for help with setting up Linux server where my scripts worked out on a first try

Can you just fix rocket output? That would be awesome

**Comment by gegtor** [comment]
Closed on accident

**Comment by Trojaner** [comment]
You should really avoid the rocketmod scripts and launcher and report the issues you face with the official way instead

**Comment by SDGNelson** [comment]
If you insist on being uncooperative, then there is not much we can do to help. 

Thanks for the backup Trojaner! ❤️

**Comment by SDGNelson** [comment]
Closing, but feel free to comment and we can troubleshoot. Either way the SDG version or custom forks of it will become mandatory in the next update.
