### ISSUE TITLE
/home command it does not work

### ISSUE THREAD

**Issue by Shalian** [SmartlyDressedGames/Legally-Distinct-Missile#20]
/ home command does not work with uessentials and other plugins

**Comment by SDGNelson** [comment]
Are you using the latest version? One of the older versions was trying to teleport the player inside the bed model, so a newer version properly offsets them vertically identical to the vanilla game.

**Comment by Shalian** [comment]
Thanks, I've fixed the issue changing essentials.command.home to rocket.home in permissions text

**Comment by SDGNelson** [comment]
Glad to hear it!
