### ISSUE TITLE
Automatic Downloader

### ISSUE THREAD

**Issue by JustOneMoreBlock** [SmartlyDressedGames/Legally-Distinct-Missile#24]
Not an issue, however, a way to automatically download the latest file. I'm sure you do provide in the extra's folder, however, peace of mind from some people.

Ubuntu/Debian
```
apt-get -y install jq curl
```

CentOS/Fedora/RedHat
```
yum -y install jq curl
```

```
        RocketMod="$(curl -sL https://api.github.com/repos/SmartlyDressedGames/Legally-Distinct-Missile/releases/latest | jq -r '.assets[].browser_download_url')"
        cd /home/Temp
        wget ${RocketMod} -O Rocket.zip
        unzip -qqo Rocket.zip
        yes | cp -rf Rocket.Unturned /home/Games/unturned/Modules/
```

GitHub API (JSON): https://api.github.com/repos/SmartlyDressedGames/Legally-Distinct-Missile/releases/latest

**Comment by Trojaner** [comment]
The latest RocketMod is always included in the Extras folder so a simple `cp` is enough, no need to hassle with GitHub releases or downloading anything.

**Comment by ennerperez** [comment]
There is no need to put rocket in extra folder, this is not a game part, its a mod, and could be great to get distance between them and unturned.

Also, this repo is for Rocket updates, the included in game depots has 0 value, cuz those breaking updates.

**Comment by SDGNelson** [comment]
@ennerperez the version included with the game is the latest from this repository. Feel free to report any breakages and I will help sort them out, but as far as I am aware all changes have been backwards compatible.

Trojaner is correct that the version in the Extras directory will always be up to date.
