### ISSUE TITLE
Libraries

### ISSUE THREAD

**Issue by Bearbored** [SmartlyDressedGames/Legally-Distinct-Missile#30]
I'm making some plugins, and i get errors by file not found of references, i add them in libraries folder (the dlls of reference) and rocket throw me file not found exceptions, was happening with I18N.West, i changed the code and i removed that, and now isn't detecting MySql.Data either. What can be the problem. i'm new to rocket, but i managed in how to code as well.

[loading] RVOEXPSystem
[registered] /exp (RVOEXPSystem.Commands.CommandExperience/exp)
Could not find dependency: I18N.West, Version=4.0.0.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756
Could not find dependency: I18N.West, Version=4.0.0.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756
RVOEXPSystem >> Could not load file or assembly 'I18N.West, Version=4.0.0.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756' or one of its dependencies.
RVOEXPSystem >> [RVO_Exp_System] Revelaos Experience System ha sido agregado correctamente.

**Comment by SDGNelson** [comment]
I think that specific dependency warning has come up before, but your best bet to get an answer on this is if another Rocket plugin developer replies.
