### ISSUE TITLE
[Bug] When it will be fixed?!

### ISSUE THREAD

**Issue by surv0013** [SmartlyDressedGames/Legally-Distinct-Missile#39]
Event `onCheckValid` is `[Obsolete]` or what? Why does one event overlap another? Did you want to remove it? If so, why is there no attribute `[Obsolete]`? Why is the old event used in Rocket? Simply because of this, it is not possible to use the new event normally, because in this case the Rocket prefixes disappear.

P.S. Rocket v4.3.9.12

![image](https://user-images.githubusercontent.com/17459138/115075005-7e753800-9f0b-11eb-8faa-53027759c242.png)
![image](https://user-images.githubusercontent.com/17459138/115075260-df9d0b80-9f0b-11eb-91a9-1b9ec7db9e55.png)

**Comment by SDGNelson** [comment]
The WithExplanation variant was added a long time ago when an explanation string was added for plugin kicks. It superseded the older event because ideally plugins should be providing a reason.

**Comment by surv0013** [comment]
Problem is that Rocket itself uses a variant without explanation, as a result of this, if you load the plugin with an explanation, the Rocket event will stop working.

And if the Rocket event stops working, then besides the fact that there will be no prefixes, all plugins that work on the Rocket event will also stop working.

This problem can be fixed in two ways: either remove the event overriding so that they both fire, or change the event in Rocket.

P.S. I don’t need to tell you about the history of the appearance of the second event, I have been "playing" your game for 7 years now and I know where it came from. Of course, during this time I have accumulated a ton of questions about the game code, but more on that another time. :D

**Comment by SDGNelson** [comment]
No need to be rude. 🙄 

In general the intention with game plugin improvements has been for plugins to bind the game events rather than Rocket events, but I suppose this should be changed in Rocket for better backwards compatibility.

**Comment by surv0013** [comment]
> No need to be rude. 🙄

I'm not rude, I'm angry... I can understand the bugs that appeared after the update, but I do not understand the bugs that are already several years old.
![image](https://user-images.githubusercontent.com/17459138/115124752-fc514600-9fd4-11eb-83dc-3a92bfdcce99.png)

**Comment by SDGNelson** [comment]
Nobody has raised an issue about it before.
https://github.com/SmartlyDressedGames/Legally-Distinct-Missile/issues?q=is%3Aissue+onCheckValid
https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues?q=is%3Aissue+onCheckValid

![lion](https://user-images.githubusercontent.com/12567645/115128794-91d0e380-9f9d-11eb-9bb5-4027feb26c2e.jpg)

**Comment by surv0013** [comment]
Ok you convinced me

![image](https://user-images.githubusercontent.com/17459138/115136596-cc845b80-a031-11eb-83ac-58f7ac67699a.png)

**Comment by rube200** [comment]
It has not explicit but #15 could have fixed that issue (it was one of the reasons of that pr)
