### ISSUE TITLE
[Feature Request] Time printout on the console.

### ISSUE THREAD

**Issue by Lion4K** [SmartlyDressedGames/Legally-Distinct-Missile#41]
Show Time before the console printout.

so instead of:
`
Disconnecting: PlayerID: 7656119888xxxxxxx Name: xxxx Character: xxx
BattlEye Server: Player #109 xxx disconnected
Player finished session: 76561198973xxxxxx
Broadcast: xxxxxxxx saiu do servidor.
`
We get:

`
[18:05:35]Disconnecting: PlayerID: 7656119888xxxxxxx Name: xxxx Character: xxx
[18:05:36]BattlEye Server: Player #109 xxx disconnected
[18:05:37]Player finished session: 76561198973xxxxxx
[18:05:38]Broadcast: xxxxxxxx saiu do servidor.
`

And so on.

**Comment by Sl4vP0weR** [comment]
Add an empty space before text and add caller, rocketmod will look like openmod

**Comment by SDGNelson** [comment]
Would not add this to Rocket, but it might make sense in the base game. In vanilla the timestamp is visible in the log file. If you would like to customize, one option would be to subclass ICommandInputOutput or ThreadedConsoleInputOutput and prepend the timestamp.

**Comment by Lion4K** [comment]
> Would not add this to Rocket, but it might make sense in the base game. In vanilla the timestamp is visible in the log file. If you would like to customize, one option would be to subclass ICommandInputOutput or ThreadedConsoleInputOutput and prepend the timestamp.

Yeah I couldn't find the base game repo about server hosting so I posted it here.
Thanks!
