### ISSUE TITLE
[Feature Request] /A to spawn Animals by Their names instead of ID (like /I for Items), and /Z for Zombies.

### ISSUE THREAD

**Issue by Lion4K** [SmartlyDressedGames/Legally-Distinct-Missile#42]
Same way we can spawn /i Items and /v vehicles and all, a good addition would be /a for animals and /z for zombies.

**Comment by SDGNelson** [comment]
Sorry, but this is outside the scope of the project. The goal here is only to maintain backwards compatibility with Unturned. If you are interested in implementing it would be relatively straightforward to make the /A custom command. Less so the /Z command because the number of zombies is constant.
