### ISSUE TITLE
Eh. Swear in what is now official code.

### ISSUE THREAD

**Issue by Jdance-Media** [SmartlyDressedGames/Legally-Distinct-Missile#62]
https://github.com/SmartlyDressedGames/Legally-Distinct-Missile/blob/master/Rocket.Unturned/Commands/CommandGod.cs#LL27C58-L27C58

**Comment by SDGNelson** [comment]
Sven ¯\\\_(ツ)_/¯

Not even the worst in the base game - profanity filter tests include lots of foul language.
